# file: ntp/tasks/main.yaml

- name: Make sure the dependencies are installed
  apt:
    pkg: "{{item}}"
    state: present
  with_items:
    - ntp
    - ntpdate

- name: Configure ntp (/etc/ntp.conf)
  copy:
    src: etc_ntp.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart ntp
