# file: nginx/tasks/main.yaml

- name: Make sure the ansible required dependencies are installed
  apt:
    pkg: python-pycurl
    state: present

- name: Make sure nginx is installed
  apt:
    pkg: nginx-extras
    state: present
  notify:
    - restart nginx

- name: Copy the nxensite and nxdissite scripts
  template:
    src: "{{item}}.j2"
    dest: "/usr/local/sbin/{{item}}"
    owner: root
    group: root
    mode: 0755
  with_items: ["nxensite", "nxdissite"]

- name: Make sure the Nginx configuration is updated
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx

- name: Add UFW rule allow from anywhere
  ufw:
    rule: allow
    name: 'Nginx HTTP'

- include: default.yaml
