# file: tdiary/tasks/main.yaml

- name: Make sure tdiary is installed
  sudo: no
  command: /usr/local/rbenv/shims/gem install tdiary
  args:
    creates: /usr/local/rbenv/shims/tdiary

- name: Make sure /opt/tdiary directory is present
  file:
    path: /opt/tdiary
    state: directory

- name: Create a new diary
  command: /usr/local/rbenv/shims/tdiary new diary --skip-bundle
  args:
    chdir: /opt/tdiary
    creates: /opt/tdiary/diary/

- name: Clone tdiary-contrib
  git:
    repo: git://github.com/senosa/tdiary-contrib.git
    dest: /opt/tdiary/contrib

- name: Copy tdiary.conf
  template:
    src: tdiary.conf.j2
    dest: /opt/tdiary/diary/tdiary.conf

- name: Copy .htpasswd
  template:
    src: htpasswd.j2
    dest: /opt/tdiary/diary/.htpasswd

- name: Copy Gemfile.local
  copy:
    src: Gemfile.local
    dest: /opt/tdiary/diary/Gemfile.local

- name: Copy unicorn.conf
  copy:
    src: unicorn.conf
    dest: /opt/tdiary/diary/unicorn.conf

- name: Copy config.ru
  copy:
    src: config.ru
    dest: /opt/tdiary/diary/config.ru

- name: Copy feed icon
  copy:
    src: feed-icon-16x16.png
    dest: /opt/tdiary/diary/public/feed-icon-16x16.png

- name: Copy my plugins
  copy:
    src: plugin
    dest: /opt/tdiary/diary/misc

- name: Copy my themes
  copy:
    src: theme
    dest: /opt/tdiary/diary

- name: Chown main_user (/opt/tdiary)
  command: chown -R {{main_user}}:{{main_user}} /opt/tdiary
  changed_when: False

- name: Bundle install
  sudo: no
  command: /usr/local/rbenv/shims/bundle install --path vendor/bundle --without test development
  args:
    chdir: /opt/tdiary/diary
  register: result
  changed_when: result.stdout | search("Installing")

- name: Make sure data directory is present
  file:
    path: /opt/tdiary/data
    state: directory

- name: Chown www-data (/opt/tdiary)
  command: chown -R www-data:www-data /opt/tdiary
  changed_when: False

- name: Make sure log directory is present
  file:
    path: /var/log/tdiary
    state: directory
    owner: www-data
    group: adm
    mode: 0750

- name: Copy upstart script
  copy:
    src: etc_init_tdiary.conf
    dest: /etc/init/tdiary.conf
  notify:
    - restart tdiary
