# file: bash/tasks/main.yaml

- name: Enable color prompt
  lineinfile:
    dest: /home/{{ main_user }}/.bashrc
    insertafter: '^#force_color_prompt=yes'
    line: 'force_color_prompt=yes'
    backup: yes

- name: Set LANG=ja_JP.UTF-8
  lineinfile:
    dest: /home/{{ main_user }}/.bashrc
    line: 'export LANG=ja_JP.UTF-8'
