---

- hosts: all
  sudo: yes
  vars_files:
    - vars/common.yaml
    - vars/private.yaml
  roles:
    - { role: apt, tags: [ 'apt' ] }
    - { role: timezone, tags: [ 'timezone' ] }
    - { role: ntp, tags: [ 'ntp' ] }
    - { role: hostname, tags: [ 'hostname' ] }
    - { role: openssh, tags: [ 'openssh' ] }
    - { role: postfix, tags: [ 'postfix' ] }
    - { role: logwatch, tags: [ 'logwatch' ] }
    - { role: fail2ban, tags: [ 'fail2ban' ] }
    - { role: monit, tags: [ 'monit' ] }
    - { role: ufw, tags: [ 'ufw' ] }
    - { role: utils, tags: [ 'utils' ] }
    - { role: bash, tags: [ 'bash' ], sudo: no}
    # - { role: tig, tags: [ 'tig' ] }
