---

- hosts: all
  sudo: yes
  vars_files:
    - vars/common.yaml
    - vars/private.yaml
  roles:
    - { role: timezone, tags: [ 'timezone' ] }
    - { role: hostname, tags: [ 'hostname' ] }
    - { role: openssh, tags: [ 'openssh' ] }
    - { role: ufw, tags: [ 'ufw' ] }
    - { role: bash, tags: [ 'bash' ], sudo: no}
    # - Ansibles.apt
    # - Ansibles.hostname
    # - Ansibles.timezone
    # - { role: utils, tags: [ 'utils' ] }
    # - { role: ufw, tags: [ 'ufw' ] }
    # - Ansibles.openssh
    # - Ansibles.vim
    # - { role: postfix, tags: [ 'postfix' ] }
    # - { role: Ansibles.ntp, tags: [ 'ntp' ] }
    # - { role: Ansibles.logwatch, tags: [ 'logwatch' ] }
    # - { role: Ansibles.monit, tags: [ 'monit' ] }
    # - { role: Ansibles.fail2ban, tags: [ 'fail2ban' ] }
    # - { role: Ansibles.git, tags: [ 'git' ] }
    # - { role: tig, tags: [ 'tig' ] }
