---

- hosts: all
  sudo: yes
  vars_files:
    - vars/common.yaml
    - vars/private.yaml
  roles:
    - Ansibles.apt
    - Ansibles.hostname
    - Ansibles.timezone
    - Ansibles.openssh
    - Ansibles.vim
    - { role: postfix, tags: [ 'postfix' ] }
    - { role: Ansibles.logwatch, tags: [ 'logwatch' ] }
