---

- hosts: all
  sudo: yes
  vars_files:
    - vars/common.yaml
    - vars/private.yaml
  roles:
    - Ansibles.apt
    - Ansibles.hostname
    - Ansibles.timezone
    - Ansibles.openssh
    - Ansibles.vim
    - { role: postfix, tags: [ 'postfix' ] }
    - { role: Ansibles.ntp, tags: [ 'ntp' ] }
    - { role: Ansibles.logwatch, tags: [ 'logwatch' ] }
    - { role: Ansibles.monit, tags: [ 'monit' ] }
    - { role: Ansibles.fail2ban, tags: [ 'fail2ban' ] }
    - { role: Ansibles.git, tags: [ 'git' ] }
    - { role: tig, tags: [ 'tig' ] }
    - { role: utils, tags: [ 'utils' ] }
