# file: postfix/tasks/main.yaml

- name: Make sure Postfix are installed
  apt:
    pkg: "{{item}}"
    state: present
  with_items: ["postfix", "mailutils"]

- name: Configure Postfix (/etc/postfix/main.cf)
  template:
    src: etc_postfix_main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  notify: restart postfix

- name: Configure Postfix (/etc/postfix/sasl_passwd)
  template:
    src: etc_postfix_sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    owner: root
    group: root
    mode: 0600
  notify: postmap sasl_passwd

- name: Configure aliases (/etc/aliases)
  copy:
    src: etc_aliases
    dest: /etc/aliases
  notify: newaliases
