---
# Defines tasks applicable for postfix

- name: Install Postfix and related packages
  sudo: yes
  apt: pkg={{ item }} state=installed
  with_items:
    - postfix
    - mailutils
  tags: postfix

- name: Replace /etc/postfix/main.cf
  sudo: yes
  copy: src=etc_postfix_main.cf dest=/etc/postfix/main.cf backup=yes
  notify: restart postfix
  tags: postfix

- name: Copy /etc/postfix/sasl_passwd
  sudo: yes
  template: src=etc_postfix_sasl_passwd.j2 dest=/etc/postfix/sasl_passwd owner=root group=root mode=0600 backup=yes
  notify: restart postfix
  tags: postfix

- name: Run postmap
  sudo: yes
  shell: postmap /etc/postfix/sasl_passwd
  notify: restart postfix
  tags: postfix

- name: Replace /etc/aliases
  sudo: yes
  copy: src=etc_aliases dest=/etc/aliases backup=yes
  tags: postfix

- name: Run newaliases
  sudo: yes
  shell: newaliases
  tags: postfix
