# file: tig/tasks/install.yaml

- name: Make sure the build dependencies are installed
  apt:
    pkg: "libncursesw5-dev"
    state: present

- name: Make sure github is in the known_hosts file
  known_hosts:
    host: github.com
    state: present

- name: Clone the tig repository in /tmp
  git:
    repo: git://github.com/jonas/tig.git
    version: tig-{{tig_version}}
    dest: /tmp/tig

- name: Checkout local branch from tag
  command: git checkout -b build-{{tig_version}} chdir=/tmp/tig

- name: Build tig from source - pt. 1 (Make)
  shell: LDLIBS=-lncursesw CFLAGS=-I/usr/include/ncursesw make prefix={{tig_prefix}} chdir=/tmp/tig

- name: Build tig from source - pt. 2 (Make install)
  command: make install prefix={{tig_prefix}} chdir=/tmp/tig
