# file: tig/tasks/main.yaml

- name: Check tig version
  command: tig --version
  register: result
  changed_when: false
  failed_when: result.rc not in [0,2]

- include: install.yaml
  when: result.rc == 2 or result.stdout != "tig version {{tig_version}}"
