# file: zsh/tasks/main.yaml

- name: Make sure zsh is installed
  sudo: yes
  apt:
    pkg: zsh
    state: present

- name: Make sure homesick gem is installed
  sudo: yes
  gem:
    name: homesick
    state: present
    user_install: no

- name: Make sure github is in the known_hosts file
  known_hosts:
    host: github.com
    state: present

- name: Clone oh-my-zsh
  git:
    repo: git://github.com/robbyrussell/oh-my-zsh.git
    dest: /home/{{main_user}}/.oh-my-zsh
    update: no
    depth: 1

- name: Clone dircolors-solarized
  git:
    repo: git://github.com/seebi/dircolors-solarized.git
    dest: /home/{{main_user}}/src/dircolors-solarized
    update: no
    depth: 1

- name: Symlink dircolors-solarized
  file:
    src: /home/{{main_user}}/src/dircolors-solarized/dircolors.256dark
    dest: /home/{{main_user}}/.dircolors
    state: link

- name: Clone my dotfiles by homesick
  shell: cd; bash -lc "homesick clone git@github.com:senosa/dotfiles"
  changed_when: false

- name: Symlink my dotfiles by homesick
  shell: cd; bash -lc "homesick link --force"
  changed_when: false

- name: Change default shell
  sudo: yes
  user:
    name: "{{main_user}}"
    shell: /usr/bin/zsh
