- name: Add rule for OpenSSH allow from anywhere
  ufw:
    rule: allow
    name: OpenSSH

- name: Add rule for mosh allow from anywhere
  ufw:
    rule: allow
    name: mosh

- name: Enable log for ufw
  ufw:
    logging: low

- name: Enable ufw
  ufw:
    state: enabled
