# file: utils/tasks/main.yaml

- name: Add PPA
  apt_repository:
    repo: ppa:git-core/ppa

- name: Make sure some basic utilities are installed
  apt:
    pkg: "{{item}}"
    state: present
  with_items:
    - dstat
    - git
    - htop
    - ifstat
    - iftop
    - iotop
    - language-pack-ja
    - linux-headers-generic
    - mosh
    - source-highlight
    - tmux
    - vim-nox
    - w3m

- name: Make sure vim-tiny is uninstalled
  apt:
    pkg: vim-tiny
    state: absent

- name: Update alternatives editor to vim-nox
  command: update-alternatives --set editor /usr/bin/vim.nox

- name: Add rule for mosh allow from anywhere
  ufw:
    rule: allow
    name: mosh

- name: Copy gitconfig for root (etckeeper)
  template:
    src: gitconfig.j2
    dest: /root/.gitconfig
