---
# Defines tasks applicable across all machines in the infrastructure.

- include: apt.yaml
  sudo: yes

- name: Change timezone UTC to JST
  sudo: yes
  when: ansible_date_time.tz == "UTC"
  command: "{{ item }}"
  with_items:
   - mv /etc/localtime /etc/localtime.orig
   - cp /usr/share/zoneinfo/Japan /etc/localtime

- name: Configure sshd_config
  sudo: yes
  lineinfile: dest=/etc/ssh/sshd_config backup=yes {{ item }}
  with_items:
    - regexp='^PasswordAuthentication' line='PasswordAuthentication no' insertafter='#PasswordAuthentication'
    - regexp='^UsePAM' line='UsePAM no' insertafter='#UsePAM'
  notify: restart ssh

- include: ufw.yaml
  sudo: yes

- name: Ensure github is in the known_hosts file
  known_hosts: host=github.com state=present
