---
# Defines tasks applicable for rbenv

- name: Install ruby building dependencies
  sudo: yes
  apt: pkg={{ item }} state=installed
  with_items:
    - git-core
    - zlib1g-dev
    - build-essential
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt1-dev
    - libcurl4-openssl-dev
    - python-software-properties

- name: Clone rbenv
  git: repo=git://github.com/sstephenson/rbenv.git dest=~{{ main_user }}/.rbenv

- name: Clone ruby-build
  git: repo=git://github.com/sstephenson/ruby-build.git dest=~{{ main_user }}/.rbenv/plugins/ruby-build

- name: Ensure fragments bash dir exists
  file: dest=~{{ main_user }}/.bash.d/ state=directory

- name: Copy rbenv bash file
  copy: src=50_rbenv.bash dest=~{{ main_user }}/.bash.d/50_rbenv.bash mode=700 owner={{ main_user }}

- name: Source rbenv bash file in dot bash_profile
  lineinfile: dest=~{{ main_user }}/.bash_profile line="source ~/.bash.d/50_rbenv.bash" create=yes
